name: CI/CD Pipeline

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        language: [python, node]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      if: matrix.language == 'python'
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Python dependencies
      if: matrix.language == 'python'
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt

    - name: Run Python tests
      if: matrix.language == 'python'
      run: |
        python -m unittest discover -s backend/tests

    - name: Set up Node.js
      if: matrix.language == 'node'
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Node.js dependencies
      if: matrix.language == 'node'
      run: |
        cd frontend
        npm install

    - name: Run Node.js tests
      if: matrix.language == 'node'
      run: |
        cd frontend
        npm test

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt

    - name: Deploy Python app
      run: |
        echo "Deploying Python app..."
        # Add your Python deployment commands here
        # Example:
        # scp -r backend/* user@server:/path/to/deploy

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Node.js dependencies
      run: |
        cd frontend
        npm install

    - name: Deploy Node.js app
      run: |
        echo "Deploying Node.js app..."
        # Add your Node.js deployment commands here
        # Example:
        # scp -r frontend/* user@server:/path/to/deploy
